"""add delivery status

Revision ID: 40d07c7b904e
Revises: 
Create Date: 2026-06-12 20:28:28.905594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d07c7b904e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status',sa.String(length=30),nullable=False,server_default='pending')
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
